### PR TITLE
CircularDoubly LinkedList

### PR DESCRIPTION
**Pull request by swstkswstk**
This program creates a special type of linked list called a circular doubly linked list. Each piece (or node) in the list has a link to the next and previous pieces, forming a circle.

Node: A structure that holds data and links to the next and previous nodes.

CircularDoublyLinkedList: A class that manages the list, including adding new nodes and displaying the list.

insert(data): Adds a new piece to the end of the list.

display(): Shows all the pieces in the list.

In the main part of the program, nodes with values 1, 2, 3, and 4 are added to the list and then displayed. The list forms a circle, so you can go through it continuously.

### CODE REVIEW

**Comment by swstkswstk** [comment]
please assign me this under hacktober fest

**Review by panditakshay402 — CHANGES_REQUESTED** [review]
@swstkswstk kindly follow all the rule from readme.md

**Comment by swstkswstk** [comment]
Bruh, I have followed you and starred the project, which contributes to me following all the rules in the README.md.

**Comment by swstkswstk** [comment]
image
Bruh, can you look into this once?

**Comment by panditakshay402** [comment]
> image Bruh, can you look into this once?

@swstkswstk try another repo

**Comment by swstkswstk** [comment]
Ok bruh i could , but you have the labels right for the hacktober fest ,so I just requested that kindly look into it ,others might be facing similar issues or might be unaware and their contribution for hacktober fest might go in vain , if you could fix it , might  be helpful for others as well.

**Pull request closed without merging**
