### PR TITLE
Create Matrix multiplication.cpp

### PR DESCRIPTION
**Pull request by Ishika0-0**
added matrix multiplication in C++
solved issue #350

### CODE REVIEW

**Review by panditakshay402 — APPROVED** [review]

**Comment by Ishika0-0** [comment]
@panditakshay402 
kindly merge the issue under hacktoberfest2024

**Comment by panditakshay402** [comment]
> @panditakshay402 kindly merge the issue under hacktoberfest2024

@Ishika0-0 you can check on hacktoberfest2024 website that its accepted.

**Comment by Ishika0-0** [comment]
actually it says the repo is excluded

**Comment by panditakshay402** [comment]
@Ishika0-0  hey then try this repo ``` https://github.com/panditakshay402/HACKTOBERFEST_2024 ``` this repo might be excluded due to spam!!

**Pull request merged**
