### PR TITLE
Sumant7

### PR DESCRIPTION
**Pull request by sumant7**

### CODE REVIEW

**Review by panditakshay402 — CHANGES_REQUESTED** [review]
@sumant7  Must be follow the Rules from Readme.md to get PR merged.

**Comment by sumant7** [comment]
The rules were to create a new branch and change and commit, that's what I did.

**Comment by panditakshay402** [comment]
> The rules were to create a new branch and change and commit, that's what I did.

@sumant7  until you you follow all the rules **Workflow checks will not Approve** read the Readme.md file properly **How to participate** sections

**Comment by sumant7** [comment]
> > The rules were to create a new branch and change and commit, that's what I did.
> 
> @sumant7  until you you follow all the rules **Workflow checks will not Approve** read the Readme.md file properly **How to participate** sections

I already followed and started, do I need to raise a new PR?

**Comment by panditakshay402** [comment]
> > > The rules were to create a new branch and change and commit, that's what I did.
> > 
> > 
> > @sumant7  until you you follow all the rules **Workflow checks will not Approve** read the Readme.md file properly **How to participate** sections
> 
> I already followed and started, do I need to raise a new PR?
@sumant7 
wait sometime its will updated automatically

**Pull request merged**
